# importing libaries

In [57]:
import pandas as pd
import sqlite3
import sqlalchemy
from sqlalchemy import create_engine

pg_url = 'postgresql+psycopg2://postgres:postgres@localhost:5432/demo'

engine = create_engine(pg_url, pool_recycle=-1)

print('Engine created successfully')

df = pd.read_csv("/home/tina/intermidiate_sessions/udemy_courses.csv")

df.to_sql('Udemy_Course', con=engine, index=False)

print("Done"),

Engine created successfully
Done

(None,)

In [58]:
df.head(10)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance
5,192870,Trading Penny Stocks: A Guide for All Levels I...,https://www.udemy.com/trading-penny-stocks-a-g...,True,150,9221,138,25,All Levels,3.0,2014-05-02T15:13:30Z,Business Finance
6,739964,Investing And Trading For Beginners: Mastering...,https://www.udemy.com/investing-and-trading-fo...,True,65,1540,178,26,Beginner Level,1.0,2016-02-21T18:23:12Z,Business Finance
7,403100,"Trading Stock Chart Patterns For Immediate, Ex...",https://www.udemy.com/trading-chart-patterns-f...,True,95,2917,148,23,All Levels,2.5,2015-01-30T22:13:03Z,Business Finance
8,476268,Options Trading 3 : Advanced Stock Profit and ...,https://www.udemy.com/day-trading-stock-option...,True,195,5172,34,38,Expert Level,2.5,2015-05-28T00:14:03Z,Business Finance
9,1167710,The Only Investment Strategy You Need For Your...,https://www.udemy.com/the-only-investment-stra...,True,200,827,14,15,All Levels,1.0,2017-04-18T18:13:32Z,Business Finance

In [59]:
# define a query function
def query_db(query: str, db_conn: sqlalchemy.engine.base.Connection) -> pd.DataFrame:
    df = pd.read_sql(query, db_conn)
    #print(df)
    return df

query_db("SELECT * FROM my_udemy_course LIMIT 5", engine)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance

In [68]:
query_db("""select course_title, num_subscribers from My_Udemy_Course where course_id = (
select course_id from My_Udemy_Course
    where EXTRACT(MONTH FROM published_timestamp::date) = 1 
    order by num_subscribers desc
    limit 1
)
""", engine)            # 1 at end of the where clause for published _time stamp signifies the first month in other to get a different month you can input the month num

            course_title  num_subscribers
0  Javascript Essentials            47062

# Write a query for paid courses, showing the course with the highest sales per month

In [73]:
query_db("""select course_title,price from My_Udemy_Course where course_id = (
select course_id from My_Udemy_Course
    where EXTRACT(MONTH FROM published_timestamp::date) = 1 
    order by price desc
    limit 1
)
""", engine)

                         course_title  price
0  Ultimate Investment Banking Course    200